name: Release

on:
  push:
    tags: ["v*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  snap:
    name: Release snap
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
          - os: ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out the code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Check versions match
        run: |
          version="$(grep -m1 -Po "version = \"\K[^\"]+" Cargo.toml)"
          if [[ "v${version}" != "${GITHUB_REF#refs/*/}" ]]; then
            echo "Cargo package version and tag do not match; refusing to continue."
            exit 1
          fi

      - name: Setup LXD
        uses: canonical/setup-lxd@v1

      - name: Setup Snapcraft
        run: sudo snap install --classic snapcraft

      - name: Build snap
        run: snapcraft --verbose

      - name: Release snap
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_SECRET }}
        run: |
          snapcraft upload theme-sync_*.snap --release latest/candidate
